var SCENARIOS = [
  { id: 'S01', role: 'student', difficulty: 'easy', title: 'AI 虛構文獻事件', file: 'scenarios/student/S01-easy-ai-writing.html' },
  { id: 'T01', role: 'teacher', difficulty: 'easy', title: 'AI 虛構文獻事件', file: 'scenarios/teacher/T01-easy-ai-writing.html' },
  { id: 'A01', role: 'admin', difficulty: 'easy', title: 'AI 虛構文獻事件', file: 'scenarios/admin/A01-easy-ai-writing.html' },
  { id: 'S02', role: 'student', difficulty: 'medium', title: '台師大抽血換學分', file: 'scenarios/student/S02-medium-blood-research.html' },
  { id: 'T02', role: 'teacher', difficulty: 'medium', title: '台師大抽血換學分', file: 'scenarios/teacher/T02-medium-blood-research.html' },
  { id: 'A02', role: 'admin', difficulty: 'medium', title: '台師大抽血換學分', file: 'scenarios/admin/A02-medium-blood-research.html' },
  { id: 'S03', role: 'student', difficulty: 'easy', title: '中一中科展抄襲', file: 'scenarios/student/S03-easy-science-fair.html' },
  { id: 'T03', role: 'teacher', difficulty: 'easy', title: '中一中科展抄襲', file: 'scenarios/teacher/T03-easy-science-fair.html' },
  { id: 'S04', role: 'student', difficulty: 'medium', title: '警大校長論文抄襲', file: 'scenarios/student/S04-medium-police-thesis.html' },
  { id: 'T04', role: 'teacher', difficulty: 'medium', title: '警大校長論文抄襲', file: 'scenarios/teacher/T04-medium-police-thesis.html' },
  { id: 'A04', role: 'admin', difficulty: 'medium', title: '警大校長論文抄襲', file: 'scenarios/admin/A04-medium-police-thesis.html' },
  { id: 'S05', role: 'student', difficulty: 'hard', title: '台大副校長經歷造假', file: 'scenarios/student/S05-hard-ntu-vp-fraud.html' },
  { id: 'T05', role: 'teacher', difficulty: 'hard', title: '台大副校長經歷造假', file: 'scenarios/teacher/T05-hard-ntu-vp-fraud.html' },
  { id: 'A05', role: 'admin', difficulty: 'hard', title: '台大副校長經歷造假', file: 'scenarios/admin/A05-hard-ntu-vp-fraud.html' },
  { id: 'S06', role: 'student', difficulty: 'medium', title: '假教授應徵台大', file: 'scenarios/student/S06-medium-fake-professor.html' },
  { id: 'T06', role: 'teacher', difficulty: 'medium', title: '假教授應徵台大', file: 'scenarios/teacher/T06-medium-fake-professor.html' },
  { id: 'A06', role: 'admin', difficulty: 'medium', title: '假教授應徵台大', file: 'scenarios/admin/A06-medium-fake-professor.html' },
  { id: 'S07', role: 'student', difficulty: 'hard', title: '復旦博士抄襲台灣論文', file: 'scenarios/student/S07-hard-china-plagiarism.html' },
  { id: 'T07', role: 'teacher', difficulty: 'hard', title: '復旦博士抄襲台灣論文', file: 'scenarios/teacher/T07-hard-china-plagiarism.html' },
  { id: 'A07', role: 'admin', difficulty: 'hard', title: '復旦博士抄襲台灣論文', file: 'scenarios/admin/A07-hard-china-plagiarism.html' },
  { id: 'S08', role: 'student', difficulty: 'hard', title: '中正教授遭冒名投稿', file: 'scenarios/student/S08-hard-impersonated-submission.html' },
  { id: 'T08', role: 'teacher', difficulty: 'hard', title: '中正教授遭冒名投稿', file: 'scenarios/teacher/T08-hard-impersonated-submission.html' },
  { id: 'A08', role: 'admin', difficulty: 'hard', title: '中正教授遭冒名投稿', file: 'scenarios/admin/A08-hard-impersonated-submission.html' },
  { id: 'S09', role: 'student', difficulty: 'hard', title: '北科大研究生輕生', file: 'scenarios/student/S09-hard-graduate-student-tragedy.html' },
  { id: 'T09', role: 'teacher', difficulty: 'hard', title: '北科大研究生輕生', file: 'scenarios/teacher/T09-hard-graduate-student-tragedy.html' },
  { id: 'A09', role: 'admin', difficulty: 'hard', title: '北科大研究生輕生', file: 'scenarios/admin/A09-hard-graduate-student-tragedy.html' },
  { id: 'S10', role: 'student', difficulty: 'hard', title: '台中科大校長一稿兩投', file: 'scenarios/student/S10-hard-dual-funding.html' },
  { id: 'T10', role: 'teacher', difficulty: 'hard', title: '台中科大校長一稿兩投', file: 'scenarios/teacher/T10-hard-dual-funding.html' },
  { id: 'A10', role: 'admin', difficulty: 'hard', title: '台中科大校長一稿兩投', file: 'scenarios/admin/A10-hard-dual-funding.html' },
  { id: 'S11', role: 'student', difficulty: 'medium', title: '勞動部高官博抄碩', file: 'scenarios/student/S11-medium-official-thesis.html' },
  { id: 'T11', role: 'teacher', difficulty: 'medium', title: '勞動部高官博抄碩', file: 'scenarios/teacher/T11-medium-official-thesis.html' },
  { id: 'A11', role: 'admin', difficulty: 'medium', title: '勞動部高官博抄碩', file: 'scenarios/admin/A11-medium-official-thesis.html' },
  { id: 'S12', role: 'student', difficulty: 'hard', title: '博士論文抄襲爭議', file: 'scenarios/student/S12-hard-thesis-plagiarism.html' },
  { id: 'T12', role: 'teacher', difficulty: 'hard', title: '博士論文抄襲爭議', file: 'scenarios/teacher/T12-hard-thesis-plagiarism.html' },
  { id: 'A12', role: 'admin', difficulty: 'hard', title: '博士論文抄襲爭議', file: 'scenarios/admin/A12-hard-thesis-plagiarism.html' }
];
